set(CZMAKE_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/../ CACHE INTERNAL "")
include(${CMAKE_CURRENT_LIST_DIR}/czmake/misc.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/czmake/sip.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/czmake/subversion.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/czmake/library.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/czmake/dependencies.cmake)
