include(${CMAKE_CURRENT_LIST_DIR}/private/misc.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/private/sip.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/private/subversion.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/private/library.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/private/dependencies.cmake)
