set(CZMAKE_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/czmake CACHE INTERNAL "")
include(czmake/misc.cmake)
include(czmake/sip.cmake)
include(czmake/subversion.cmake)
include(czmake/library.cmake)
include(czmake/dependencies.cmake)
